export const PAGE_CONFIG = {
  A4_WIDTH_MM: 210,
  A4_HEIGHT_MM: 297,
  A4_WIDTH_PX: 794, // 210mm at 96 DPI
  A4_HEIGHT_PX: 1123, // 297mm at 96 DPI
  MARGIN_MM: 20,
  MARGIN_PX: 76, // 20mm at 96 DPI
  HEADER_HEIGHT_PX: 60,
  FOOTER_HEIGHT_PX: 60,
};

export const EDITOR_CONFIG = {
  CONTENT_WIDTH: PAGE_CONFIG.A4_WIDTH_PX - PAGE_CONFIG.MARGIN_PX * 2,
  CONTENT_HEIGHT:
    PAGE_CONFIG.A4_HEIGHT_PX -
    PAGE_CONFIG.MARGIN_PX * 2 -
    PAGE_CONFIG.HEADER_HEIGHT_PX -
    PAGE_CONFIG.FOOTER_HEIGHT_PX,
};
